"""A synthetic simulator run in the delivered export format — for tests only.

It writes exactly what the simulator writes (``settings.json``, ``observations.csv``,
``skyline/images/*.png``, ``skyline/sim/*_sky.png``) with **constructed** poses and **constructed**
skylines, so the adapter can be tested end-to-end without a single byte of real simulator output.

The known answers this fixture provides are what make the tests known-answer tests:

* every pose is chosen, so the expected ENU position and compass heading are known exactly;
* the sky mask is drawn from a chosen row profile, so the expected GT skyline curve is known exactly;
* the quaternion is generated by the same declared convention the adapter identifies, so a test can
  corrupt it deliberately and check that the adapter notices.

Nothing here is a claim about what the simulator produces; it is a claim about what the *format*
says, which is the thing the adapter is written against.
"""

from __future__ import annotations

import csv
import json
import struct
import zlib
from pathlib import Path

import numpy as np

from hsreloc.simret.conventions import ue_rotator_to_quaternion

DEFAULT_W, DEFAULT_H = 64, 48


def _png_chunk(tag: bytes, data: bytes) -> bytes:
    return (struct.pack(">I", len(data)) + tag + data
            + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))


def write_png(path: Path, array: np.ndarray) -> Path:
    """Minimal 8-bit PNG writer (grey or RGB) so fixtures need no image library."""
    a = np.asarray(array, dtype=np.uint8)
    if a.ndim == 2:
        colour, channels = 0, 1
    elif a.ndim == 3 and a.shape[2] == 3:
        colour, channels = 2, 3
    else:
        raise ValueError(f"unsupported array shape {a.shape}")
    h, w = a.shape[:2]
    raw = b"".join(b"\x00" + a[y].tobytes() for y in range(h))
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(
        b"\x89PNG\r\n\x1a\n"
        + _png_chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, colour, 0, 0, 0))
        + _png_chunk(b"IDAT", zlib.compress(raw, 6))
        + _png_chunk(b"IEND", b""))
    return path


def mask_from_rows(rows: np.ndarray, height: int) -> np.ndarray:
    """Binary sky mask (255 above the boundary, 0 below) from a per-column boundary row.

    ``rows[x] = r`` means everything strictly above row ``r`` is sky, so the topmost contiguous sky
    run in that column ends at ``r - 1`` and the extracted boundary is ``r - 1 + 0.5``. A test that
    knows ``rows`` therefore knows the expected curve exactly.
    """
    w = len(rows)
    mask = np.zeros((height, w), dtype=np.uint8)
    for x, r in enumerate(rows):
        r = int(r)
        if r > 0:
            mask[:r, x] = 255
    return mask


def settings(run_id: str = "Run_20260831_172540", level: str = "hills_with_forest",
             width: int = DEFAULT_W, height: int = DEFAULT_H, hfov: float = 90.0,
             vfov: float = 90.0, time_of_day: str = "DAY", hour: float = 12.0,
             clouds: str = "CLEAR", heading_mode: str = "world_locked_north") -> dict:
    """The delivered ``settings.json`` shape, with intrinsics consistent with the FOVs by default."""
    fx = (width / 2.0) / np.tan(np.radians(hfov) / 2.0)
    fy = (height / 2.0) / np.tan(np.radians(vfov) / 2.0)
    return {
        "run_id": run_id, "level": level,
        "environment": {"time_of_day": time_of_day, "hour": hour, "time_speed": 0.0, "clouds": clouds},
        "north_camera": {
            "width_px": width, "height_px": height, "projection": "perspective",
            "horizontal_fov_deg": hfov, "vertical_fov_deg": vfov,
            "intrinsics_px": {"fx": round(float(fx), 6), "fy": round(float(fy), 6),
                              "cx": width / 2.0, "cy": height / 2.0},
            "distortion": "none", "heading_mode": heading_mode,
        },
        "skyline": {"automatic_capture": True, "capture_distance_m": 100.0},
    }


def default_rows(width: int, height: int, phase: float = 0.0, offset: float = 0.0) -> np.ndarray:
    """A smooth, structured skyline: a horizon with two hills. Never flat (a flat one is degenerate)."""
    x = np.linspace(0.0, 1.0, width)
    base = height * 0.45 + offset
    ridge = 4.0 * np.sin(2 * np.pi * (x + phase)) + 2.5 * np.sin(6 * np.pi * (x + phase) + 0.7)
    return np.clip(np.round(base - ridge), 1, height - 1).astype(int)


def build_run(run_dir: Path, poses: list, *, run_id: str = "Run_20260831_172540",
              level: str = "hills_with_forest", width: int = DEFAULT_W, height: int = DEFAULT_H,
              hfov: float = 90.0, vfov: float = 90.0, time_of_day: str = "DAY", hour: float = 12.0,
              clouds: str = "CLEAR", heading_mode: str = "world_locked_north",
              settings_override: dict | None = None, row_fn=None,
              quaternion_fn=ue_rotator_to_quaternion, mask_fn=None,
              nested_observations: bool = False, views: tuple = ("north",),
              west_yaw_deg: float | None = None) -> dict:
    """Write a complete run. ``poses`` is a list of dicts with UE cm/deg values.

    Each pose: ``{"x_cm", "y_cm", "z_cm", "yaw", "pitch", "roll"}`` (missing keys default to 0), plus
    an optional ``"phase"``/``"offset"`` steering the constructed skyline shape.

    ``views`` adds the 2026-09-06 dual-direction columns when it contains ``"west"``: a
    ``west_camera`` block (``world_locked_west``), ``west_ue_*`` pose columns at the *same* position
    with yaw ``pose yaw - 90`` (or ``west_yaw_deg`` when given, to build a refusal case), and a
    ``west_image_path`` / ``west_sim_sky_mask_path`` pair whose constructed skyline differs from the
    North one (phase + 0.25) so a test can tell which view was read. The default output is unchanged.
    """
    run_dir = Path(run_dir)
    cfg = settings(run_id, level, width, height, hfov, vfov, time_of_day, hour, clouds, heading_mode)
    with_west = "west" in views
    if with_west:
        cfg["west_camera"] = {**cfg["north_camera"], "heading_mode": "world_locked_west"}
        cfg["skyline"] = {**cfg["skyline"], "views": ["north", "west"],
                          "capture_pairing": "same CaptureSkylineObservation callback"}
    if settings_override:
        for key, value in settings_override.items():
            if isinstance(value, dict) and isinstance(cfg.get(key), dict):
                cfg[key] = {**cfg[key], **value}
            else:
                cfg[key] = value
    (run_dir).mkdir(parents=True, exist_ok=True)
    (run_dir / "settings.json").write_text(json.dumps(cfg, indent=2), encoding="utf-8")

    rows_out, expected = [], {}
    for i, pose in enumerate(poses):
        oid = pose.get("observation_id", f"sky_{i + 1:06d}")
        yaw = float(pose.get("yaw", 0.0))
        pitch = float(pose.get("pitch", 0.0))
        roll = float(pose.get("roll", 0.0))
        q = quaternion_fn(yaw, pitch, roll)
        rows = (row_fn or default_rows)(width, height, pose.get("phase", 0.0), pose.get("offset", 0.0))
        mask = (mask_fn or mask_from_rows)(rows, height)
        img_rel = f"skyline/images/{oid}.png"
        msk_rel = f"skyline/sim/{oid}_sky.png"
        rgb = np.zeros((height, width, 3), dtype=np.uint8)
        rgb[..., 2] = mask                                # blue where sky, black below: visibly sane
        rgb[..., 1] = (255 - mask) // 3
        write_png(run_dir / img_rel, rgb)
        write_png(run_dir / msk_rel, mask)
        row = {
            "observation_id": oid, "sim_time_s": f"{i * 0.5:.3f}",
            "north_ue_x_cm": f"{float(pose.get('x_cm', 0.0)):.3f}",
            "north_ue_y_cm": f"{float(pose.get('y_cm', 0.0)):.3f}",
            "north_ue_z_cm": f"{float(pose.get('z_cm', 0.0)):.3f}",
            "north_ue_yaw_deg": f"{yaw:.6f}", "north_ue_pitch_deg": f"{pitch:.6f}",
            "north_ue_roll_deg": f"{roll:.6f}",
            "north_ue_quat_w": f"{q[0]:.9f}", "north_ue_quat_x": f"{q[1]:.9f}",
            "north_ue_quat_y": f"{q[2]:.9f}", "north_ue_quat_z": f"{q[3]:.9f}",
            "nadir_ue_x_cm": f"{float(pose.get('x_cm', 0.0)):.3f}",
            "nadir_ue_pitch_deg": "-90.0",
            "image_path": img_rel, "sim_sky_mask_path": msk_rel,
        }
        expected[oid] = {"rows": rows, "boundary": np.array([r - 0.5 for r in rows], dtype=float)}
        if with_west:
            wyaw = (yaw - 90.0) if west_yaw_deg is None else float(west_yaw_deg)
            wq = quaternion_fn(wyaw, pitch, roll)
            wrows = (row_fn or default_rows)(width, height, pose.get("phase", 0.0) + 0.25,
                                             pose.get("offset", 0.0))
            wmask = (mask_fn or mask_from_rows)(wrows, height)
            wimg_rel = f"skyline/images/{oid}_west.png"
            wmsk_rel = f"skyline/sim/{oid}_west_sky.png"
            wrgb = np.zeros((height, width, 3), dtype=np.uint8)
            wrgb[..., 2] = wmask
            wrgb[..., 0] = (255 - wmask) // 3
            write_png(run_dir / wimg_rel, wrgb)
            write_png(run_dir / wmsk_rel, wmask)
            row.update({
                "west_ue_x_cm": row["north_ue_x_cm"], "west_ue_y_cm": row["north_ue_y_cm"],
                "west_ue_z_cm": row["north_ue_z_cm"],
                "west_ue_yaw_deg": f"{wyaw:.6f}", "west_ue_pitch_deg": f"{pitch:.6f}",
                "west_ue_roll_deg": f"{roll:.6f}",
                "west_ue_quat_w": f"{wq[0]:.9f}", "west_ue_quat_x": f"{wq[1]:.9f}",
                "west_ue_quat_y": f"{wq[2]:.9f}", "west_ue_quat_z": f"{wq[3]:.9f}",
                "west_image_path": wimg_rel, "west_sim_sky_mask_path": wmsk_rel,
            })
            expected[oid]["west_rows"] = wrows
            expected[oid]["west_boundary"] = np.array([r - 0.5 for r in wrows], dtype=float)
        rows_out.append(row)

    # The 2026-09-02 real export batch nests the table under skyline/; both layouts are exercised.
    obs_path = run_dir / ("skyline/observations.csv" if nested_observations else "observations.csv")
    obs_path.parent.mkdir(parents=True, exist_ok=True)
    with obs_path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows_out[0].keys()))
        w.writeheader()
        w.writerows(rows_out)
    return {"run_dir": run_dir, "settings": cfg, "rows": rows_out, "expected": expected,
            "width": width, "height": height}


def line_north(n: int, spacing_m: float = 10.0, east_m: float = 0.0, up_m: float = 60.0,
               yaw: float = 0.0, pitch: float = 0.0, roll: float = 0.0) -> list:
    """``n`` poses on a North-bound line at a fixed East offset — the Stage-1 trajectory shape.

    Written in UE centimetres under the PROT-001 declaration (+X = North, +Y = East) so the expected
    ENU values are ``north = x_cm/100`` and ``east = y_cm/100``.
    """
    return [{"x_cm": i * spacing_m * 100.0, "y_cm": east_m * 100.0, "z_cm": up_m * 100.0,
             "yaw": yaw, "pitch": pitch, "roll": roll, "phase": 0.03 * i}
            for i in range(n)]
